const data = [
  {
    id: 'project-1',
    type: 'layouts',
    title: 'Simple store',
    link: 'https://voverg.github.io/simple-store/',
    sourceLink: 'https://github.com/voverg/simple-store',
    img: 'img/projects/simple-store.png',
    stack: 'Html, Css, JavaScript',
    description: 'Страничка товаров интернет-магазина',
    longDescription: 'Страничка интернет-магазина с выбором товара и реализацией работающей корзины. Можно выбирать товары, смотреть в корзине их кол-во и общую стоимость, удалять товары.',
  },
  {
    id: 'project-2',
    type: 'layouts',
    title: 'Hotel landing',
    link: 'https://voverg.github.io/hotel-landing/',
    sourceLink: 'https://github.com/voverg/hotel-landing',
    img: 'img/projects/hotel-landing.png',
    stack: 'Html, Css (floats)',
    description: 'Простой лендинг отеля.',
    longDescription: 'Свёрстан на float просто для тренировки и понимания, как работает блочная модель в Css.',
  },
  {
    id: 'project-3',
    type: 'jsapps',
    title: 'Frontend quiz',
    link: 'https://voverg.github.io/50-simple-projects/frontend-quiz/index.html',
    sourceLink: 'https://github.com/voverg/50-simple-projects/tree/main/frontend-quiz',
    img: 'img/projects/frontend-quiz.png',
    stack: 'Html, Css, JavaScript',
    description: 'Викторина, в которой вы можете проверть свои знания по Html, Css и JavaScript',
    longDescription: 'Переходите по вкладкам, чтобы поучаствовать в разных викторинах. Свободно переключайтесь между вкладками, состояние вкладок запоминается.',
  },
  {
    id: 'project-4',
    type: 'jsapps',
    title: 'Kanban',
    link: 'https://voverg.github.io/simple-kanban/',
    sourceLink: 'https://github.com/voverg/simple-kanban',
    img: 'img/projects/simple-kanban.png',
    stack: 'Html, Css, JavaScript',
    description: 'Небольшое приложение на подобие Канбан',
    longDescription: 'Создавайте карточки с заметками. Редактируйте, дважды кликнув по ним. Перемещайте карточки между колонками. Удаляйте карточки, переместив их за пределы столбцов.',
  },
  {
    id: 'project-5',
    type: 'jsapps',
    title: 'Piano',
    link: 'https://voverg.github.io/50-simple-projects/piano/index.html',
    sourceLink: 'https://github.com/voverg/50-simple-projects/tree/main/piano',
    img: 'img/projects/piano.png',
    stack: 'Html, Css, JavaScript',
    description: 'Пианино, на котором можно играть как мышкой, так и с клавиатуры',
    longDescription: 'Извлекайте звуки, кликая мышкой по клавишам пианино. Либо на калвиатуре с английской расскладкой нажимайте клавиши awsedftgyhujkolp;',
  },
  {
    id: 'project-6',
    type: 'jsapps',
    title: 'Notes',
    link: 'https://voverg.github.io/50-simple-projects/notes-app/index.html',
    sourceLink: 'https://github.com/voverg/50-simple-projects/tree/main/notes-app',
    img: 'img/projects/notes-app.png',
    stack: 'Html, Css, JavaScript',
    description: 'Создавайте, удаляйте и редактируйте заметки. Для стилизации текста можно использовать Markdown.',
    longDescription: '',
  },
  {
    id: 'project-7',
    type: 'jsapps',
    title: 'Budget',
    link: 'https://voverg.github.io/budget/',
    sourceLink: 'https://github.com/voverg/budget',
    img: 'img/projects/budget.png',
    stack: 'Html, Css, JavaScript',
    description: 'Небольшое приложение по учёту доходов и расходов.',
    longDescription: '',
  },
  {
    id: 'project-8',
    type: 'jsapps',
    title: 'Clicker',
    link: 'https://voverg.github.io/50-simple-projects/game/index.html',
    sourceLink: 'https://github.com/voverg/50-simple-projects/tree/main/game',
    img: 'img/projects/clicker.png',
    stack: 'Html, Css, JavaScript',
    description: 'Игра Clicker',
    longDescription: 'Игра, в которой нужно за выбранное время попасть максимальное количество раз по шарику.',
  },
  {
    id: 'project-9',
    type: 'spa',
    title: 'Todo',
    link: 'https://voverg.github.io/todo-react/',
    sourceLink: 'https://github.com/voverg/todo-react',
    img: 'img/projects/todo-react.png',
    stack: 'Html, Css, JavaScript, React',
    description: 'Небольшое приложение - список дел',
    longDescription: 'Это первое приложение, которое я написал с использованием React. В нём используются компоненты на основе классов.',
  },
  {
    id: 'project-10',
    type: 'spa',
    title: 'Blog',
    link: 'https://voverg.github.io/react-blog/',
    sourceLink: 'https://github.com/voverg/react-blog',
    img: 'img/projects/react-blog.png',
    stack: 'Html, Css, JavaScript, Ajax, React',
    description: 'Блог с авторизацией, добавлением, удалением, поиском, сортировкой и просмотром содержимого постов, написанный на React',
    longDescription: 'Это второе приложение на React. Здесь я уже использую функциональные компоненты и простые запросы к серверу, чтобы получить список удалённых постов.',
  },
  {
    id: 'project-11',
    type: 'spa',
    title: 'Chat',
    link: 'https://voverg.github.io/chat-react/',
    sourceLink: 'https://github.com/voverg/chat-react',
    img: 'img/projects/chat.png',
    stack: 'Html, Css, JavaScript, Firebase',
    description: 'Небольшое приложение - чат в реальном времени, написанное на React + Firebase.',
    longDescription: 'Приложение написано на React с использованием функциональных компонентов и хуков. В качестве бекэнда использую Firebase.',
  },
  {
    id: 'project-12',
    type: 'spa',
    title: 'Calendar',
    link: 'https://voverg.github.io/react-calendar/',
    sourceLink: 'https://github.com/voverg/react-calendar',
    img: 'img/projects/calendar.png',
    stack: 'Html, Css, JavaScript, React, Redux, Redux Thunk',
    description: 'Приложение - календарь, написанное на React. Создавайте, просматривайте детали и удаляйте события',
    longDescription: 'Приложение написано на React с использованием функциональных компонентов и хуков. Также реализована простая авторизация. Можно заходить под разными пользователями, созадвать события и назначать их другим пользователям.',
  },
];
